{
 "title": "Server metrics",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "server", "label": "Server", "query": { "query": "label_values(server)" } }
  ]
 },
 "panels": [
  {
   "title": "Host Status Totals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count(up{job=\"node-exporter\", server=~\"$server\"} == 1) or vector(0)",
     "legendFormat": "UP"
    },
    {
     "expr": "count(up{job=\"node-exporter\", server=~\"$server\"} == 0) or vector(0)",
     "legendFormat": "DOWN"
    }
   ]
  },
  {
   "title": "Resource Health Totals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\", server=~\"$server\"}[5m])) * 100) >= 90) or vector(0)",
     "legendFormat": "CPU Critical"
    },
    {
     "expr": "count(100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\", server=~\"$server\"}[5m])) * 100) >= 80 < 90) or vector(0)",
     "legendFormat": "CPU Warning"
    },
    {
     "expr": "count((1 - (node_memory_MemAvailable_bytes{server=~\"$server\"} / node_memory_MemTotal_bytes{server=~\"$server\"})) * 100 >= 90) or vector(0)",
     "legendFormat": "RAM Critical"
    },
    {
     "expr": "count((1 - (node_memory_MemAvailable_bytes{server=~\"$server\"} / node_memory_MemTotal_bytes{server=~\"$server\"})) * 100 >= 80 < 90) or vector(0)",
     "legendFormat": "RAM Warning"
    },
    {
     "expr": "count(100 - ((node_filesystem_avail_bytes{server=~\"$server\", mountpoint=\"/\", fstype!=\"rootfs\"} / node_filesystem_size_bytes{server=~\"$server\", mountpoint=\"/\", fstype!=\"rootfs\"}) * 100) >= 90) or vector(0)",
     "legendFormat": "Disk Critical"
    },
    {
     "expr": "count(100 - ((node_filesystem_avail_bytes{server=~\"$server\", mountpoint=\"/\", fstype!=\"rootfs\"} / node_filesystem_size_bytes{server=~\"$server\", mountpoint=\"/\", fstype!=\"rootfs\"}) * 100) >= 80 < 90) or vector(0)",
     "legendFormat": "Disk Warning"
    },
    {
     "expr": "count(node_time_seconds{server=~\"$server\"} - node_boot_time_seconds{server=~\"$server\"} < 7200) or vector(0)",
     "legendFormat": "Uptime Critical"
    },
    {
     "expr": "count(node_time_seconds{server=~\"$server\"} - node_boot_time_seconds{server=~\"$server\"} < 86400) or vector(0)",
     "legendFormat": "Uptime Warning"
    }
   ]
  },
  {
   "title": "Service Status Totals (Apps/Ports)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(probe_success{server=~\"$server\"}) or vector(0)",
     "legendFormat": "TOTAL"
    },
    {
     "expr": "count(probe_success{server=~\"$server\"} == 1) or vector(0)",
     "legendFormat": "UP"
    },
    {
     "expr": "count(probe_success{server=~\"$server\"} == 0) or vector(0)",
     "legendFormat": "DOWN"
    }
   ]
  },
  { "title": "$server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 }, "repeat": "server" },
  {
   "title": "Server Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"node-exporter\",server=\"$server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "stat",
   "description": "Overall CPU busy percentage (averaged across all cores)",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\",server=\"$server\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "Sys Load",
   "type": "stat",
   "description": "System load  over all CPU cores together",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(node_load1{server=\"$server\"}) * 100 / count(count(node_cpu_seconds_total{server=\"$server\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Real RAM usage excluding cache and reclaimable memory",
   "gridPos": { "h": 6, "w": 4, "x": 11, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min((1 - (node_memory_MemAvailable_bytes{server=\"$server\"} / node_memory_MemTotal_bytes{server=\"$server\"})) * 100, 0)"
    }
   ]
  },
  {
   "title": "Root FS Used",
   "type": "gauge",
   "description": "Used Root FS",
   "gridPos": { "h": 6, "w": 4, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  (node_filesystem_size_bytes{server=\"$server\", mountpoint=\"/\", fstype!=\"rootfs\"}\n   - node_filesystem_avail_bytes{server=\"$server\", mountpoint=\"/\", fstype!=\"rootfs\"})\n  / node_filesystem_size_bytes{server=\"$server\", mountpoint=\"/\", fstype!=\"rootfs\"}\n) * 100\n"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{server=\"$server\"}"
    }
   ]
  },
  {
   "title": "RAM Avail",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{server=\"$server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{server=\"$server\"} - node_boot_time_seconds{server=\"$server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Load Average",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load1{server=\"$server\"}",
     "legendFormat": "1min"
    },
    {
     "expr": "node_load5{server=\"$server\"}",
     "legendFormat": "5min"
    },
    {
     "expr": "node_load15{server=\"$server\"}",
     "legendFormat": "15min"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{server=\"$server\"}) by (cpu))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RootFS Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{server=\"$server\",mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "HTTP/TCP Probe Overview",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "probe_success{server=\"$server\"}"
    },
    {
     "expr": "probe_http_ssl{server=\"$server\"} > 0"
    },
    {
     "expr": "(probe_ssl_earliest_cert_expiry{server=\"$server\"} - time()) / 3600 / 24"
    },
    {
     "expr": "probe_http_status_code{server=\"$server\"} > 0"
    },
    {
     "expr": "avg_over_time(probe_duration_seconds{server=\"$server\"}[1m])"
    },
    {
     "expr": "probe_tls_version_info{server=\"$server\"}"
    },
    {
     "expr": "avg_over_time(probe_dns_lookup_time_seconds{server=\"$server\"}[1m])"
    }
   ]
  },
  {
   "title": "Current Outages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "🔴 Current Server Outages",
     "type": "table",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 80 },
     "targets": [
      {
       "expr": "up{job=\"node-exporter\", server=~\"$server\"} == 0",
       "legendFormat": "Server Down"
      }
     ]
    },
    {
     "title": "⚠️ Resource Health Alerts",
     "type": "table",
     "gridPos": { "h": 5, "w": 9, "x": 6, "y": 80 },
     "targets": [
      {
       "expr": "(100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\", server=~\"$server\"}[5m])) * 100)) > 90",
       "legendFormat": "CPU Critical"
      },
      {
       "expr": "((1 - (node_memory_MemAvailable_bytes{server=~\"$server\"} / node_memory_MemTotal_bytes{server=~\"$server\"})) * 100) > 90",
       "legendFormat": "RAM Critical"
      },
      {
       "expr": "(100 - ((node_filesystem_avail_bytes{server=~\"$server\", mountpoint=\"/\", fstype!=\"rootfs\"} / node_filesystem_size_bytes{server=~\"$server\", mountpoint=\"/\", fstype!=\"rootfs\"}) * 100)) > 90",
       "legendFormat": "Disk Critical"
      },
      {
       "expr": "count(node_time_seconds{server=~\"$server\"} - node_boot_time_seconds{server=~\"$server\"} < 7200) or vector(0)",
       "legendFormat": "Uptime Critical"
      },
      {
       "expr": "(100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\", server=~\"$server\"}[5m])) * 100)) > 80 < 90",
       "legendFormat": "CPU Warning"
      },
      {
       "expr": "((1 - (node_memory_MemAvailable_bytes{server=~\"$server\"} / node_memory_MemTotal_bytes{server=~\"$server\"})) * 100) > 80 < 90",
       "legendFormat": "RAM Warning"
      },
      {
       "expr": "(100 - ((node_filesystem_avail_bytes{server=~\"$server\", mountpoint=\"/\", fstype!=\"rootfs\"} / node_filesystem_size_bytes{server=~\"$server\", mountpoint=\"/\", fstype!=\"rootfs\"}) * 100)) > 80 < 90",
       "legendFormat": "Disk warning"
      },
      {
       "expr": "count(node_time_seconds{server=~\"$server\"} - node_boot_time_seconds{server=~\"$server\"} < 86400) or vector(0)",
       "legendFormat": "Uptime Warning"
      }
     ]
    },
    {
     "title": "🔴 Current Service Outages",
     "type": "table",
     "gridPos": { "h": 5, "w": 9, "x": 15, "y": 80 },
     "targets": [
      {
       "expr": "probe_success{server=~\"$server\"} == 0",
       "legendFormat": "Service Down"
      }
     ]
    }
   ]
  }
 ]
}